export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-white px-6 py-12 text-black font-sans">
      <article className="mx-auto max-w-3xl">
        <a href="/" className="text-sm text-gray-500 underline underline-offset-4">
          Back to LVA Power Planner
        </a>

        <h1 className="mt-8 text-4xl font-bold tracking-tight">Terms of Service</h1>
        <p className="mt-3 text-sm text-gray-500">Last updated: June 2026</p>

        <div className="mt-8 space-y-8 text-gray-700">
          <section>
            <h2 className="text-2xl font-bold text-black">Agreement to these terms</h2>
            <p className="mt-3">
              By accessing or using LVA Power Planner, you agree to these Terms of Service. If you do not agree, you must not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black">Use of the service</h2>
            <p className="mt-3">
              LVA Power Planner is a software platform for planning, documenting and managing temporary power distribution systems for live events, production and AV environments.
            </p>
            <p className="mt-3">
              You must use the service lawfully and only for legitimate planning and documentation purposes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black">User responsibilities</h2>
            <p className="mt-3">You are responsible for:</p>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>Checking all project information entered into the platform.</li>
              <li>Verifying all calculations, loads, ratings, assumptions and outputs.</li>
              <li>Ensuring equipment data is accurate and suitable for the intended use.</li>
              <li>Ensuring any system design is reviewed by a competent person before installation or use.</li>
              <li>Complying with applicable laws, standards, site rules and safety requirements.</li>
              <li>Maintaining the confidentiality of your login details.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black">No certification or professional advice</h2>
            <p className="mt-3">
              LVA Power Planner is an indicative planning and documentation tool only. It may support BS 7909 documentation workflows, but it does not verify, certify or guarantee compliance with BS 7909, BS 7671, venue requirements or any other statutory or industry standard.
            </p>
            <p className="mt-3">
              The software does not provide electrical certification, engineering approval, regulatory compliance approval or professional engineering advice. Responsibility for verification, suitability, installation, inspection, testing and compliance remains with the user and competent duty holder.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black">Reports and exports</h2>
            <p className="mt-3">
              Reports and exports generated by the platform are based on user-entered data and software calculations. You must review all reports before relying on them or sharing them with clients, venues, crew or site teams.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black">Availability and changes</h2>
            <p className="mt-3">
              We aim to provide a reliable service, but we do not guarantee that the platform will be uninterrupted, error-free or available at all times. We may update, change, suspend or remove features where necessary to maintain or improve the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black">Subscriptions, trials and payment</h2>
            <p className="mt-3">
              Where paid access, trials or subscriptions are agreed, the relevant commercial terms will be confirmed separately. Access may be suspended or withdrawn if payment terms are not met or if these terms are breached.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black">Intellectual property</h2>
            <p className="mt-3">
              LVA Power Planner, including its software, branding, interface and documentation, remains the property of its owner or licensors. You must not copy, reverse engineer, resell or misuse the platform except as permitted by law or agreed in writing.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black">Limitation of liability</h2>
            <p className="mt-3">
              To the maximum extent permitted by law, LVA Power Planner and its operators shall not be liable for indirect, incidental, consequential, business, financial or operational losses arising from use of, or reliance on, the software, calculations, reports or exported information.
            </p>
            <p className="mt-3">
              Nothing in these terms excludes liability that cannot legally be excluded.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black">Account suspension or termination</h2>
            <p className="mt-3">
              We may suspend or terminate access if you breach these terms, misuse the service, create security risks, fail to meet payment obligations, or use the platform unlawfully.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black">Changes to these terms</h2>
            <p className="mt-3">
              We may update these Terms of Service from time to time. Continued use of the service after updates are published means you accept the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-black">Contact</h2>
            <p className="mt-3">
              For questions about these terms, contact{" "}
              <a href="mailto:hello@lvapowerplanner.com" className="font-semibold underline underline-offset-4">
                hello@lvapowerplanner.com
              </a>.
            </p>
          </section>
        </div>
      </article>
    </main>
  );
}
