import type { EquipmentItem } from "./types";

export const equipmentLibrary: EquipmentItem[] = [
  {"id": "e0", "category": "Audio - Control", "name": "A&H QU16", "watts": 95},
  {"id": "e1", "category": "Audio - Control", "name": "A&H SQ5", "watts": 75},
  {"id": "e2", "category": "Audio - Control", "name": "A&H SQ7", "watts": 110},
  {"id": "e3", "category": "Audio - Control", "name": "A&H AB168", "watts": 40},
  {"id": "e4", "category": "Audio - Control", "name": "A&H AR2412", "watts": 70},
  {"id": "e5", "category": "Audio - Control", "name": "Yamaha CL", "watts": 170},
  {"id": "e6", "category": "Audio - Control", "name": "Yamaha QL", "watts": 200},
  {"id": "e7", "category": "Audio - Control", "name": "Yamaha DM3", "watts": 43},
  {"id": "e8", "category": "Audio - Control", "name": "Yamaha DM7", "watts": 240},
  {"id": "e9", "category": "Audio - Control", "name": "Yamaha DM7-C", "watts": 240},
  {"id": "e10", "category": "Audio - Control", "name": "RIO 1608", "watts": 72},
  {"id": "e11", "category": "Audio - Control", "name": "RIO 3224", "watts": 120},
  {"id": "e12", "category": "Audio - Amps", "name": "XTi 4002", "watts": 2415},
  {"id": "e13", "category": "Audio - Amps", "name": "D&B D6", "watts": 1000},
  {"id": "e14", "category": "Audio - Amps", "name": "D&B D12", "watts": 1150},
  {"id": "e15", "category": "Audio - Amps", "name": "D&B D20", "watts": 2110},
  {"id": "e16", "category": "Audio - Amps", "name": "D&B D40", "watts": 2990},
  {"id": "e17", "category": "Audio - Amps", "name": "D&B D80", "watts": 3680},
  {"id": "e18", "category": "Audio - Other", "name": "EW DX EM4", "watts": 37},
  {"id": "e19", "category": "Audio - Other", "name": "Macbook", "watts": 96},
  {"id": "e20", "category": "Lighting - Control", "name": "Avo Quartz", "watts": 80},
  {"id": "e21", "category": "Lighting - Control", "name": "Avo TigerTouch II", "watts": 80},
  {"id": "e22", "category": "Lighting - Control", "name": "Grand MA", "watts": 300},
  {"id": "e23", "category": "Lighting - Control", "name": "Artnet Rack", "watts": 80},
  {"id": "e24", "category": "Lighting - LED Generics", "name": "Chauvet Eve F-50Z Fresnel", "watts": 58},
  {"id": "e25", "category": "Lighting - LED Generics", "name": "Chauvet Ovation E-260WW IP", "watts": 213},
  {"id": "e26", "category": "Lighting - LED Generics", "name": "Chauvet Ovation E-2 FC Profile", "watts": 220},
  {"id": "e27", "category": "Lighting - LED Generics", "name": "Chauvet Ovation F265WW LED Fresnel", "watts": 231},
  {"id": "e28", "category": "Lighting - LED Pars", "name": "Chauvet Colorado 1 Tri-7 Tour", "watts": 47},
  {"id": "e29", "category": "Lighting - LED Pars", "name": "Chauvet Colorado Tour 1 30º", "watts": 70},
  {"id": "e30", "category": "Lighting - LED Pars", "name": "Chauvet Colorado 1 Quad Zoom IP", "watts": 106},
  {"id": "e31", "category": "Lighting - LED Pars", "name": "Chauvet Colorado Tour 1 Tri IP V2 15º", "watts": 96},
  {"id": "e32", "category": "Lighting - LED Pars", "name": "Chauvet Colordash Accent 3", "watts": 20},
  {"id": "e33", "category": "Lighting - LED Pars", "name": "LEDJ Spectra Par 15Q8", "watts": 130},
  {"id": "e34", "category": "Lighting - LED Pars", "name": "Chroma-Q Colour Punch", "watts": 80},
  {"id": "e35", "category": "Lighting - LED Battens", "name": "Chauvet Colorado Batten 144 Tour", "watts": 169},
  {"id": "e36", "category": "Lighting - LED Battens", "name": "Chauvet COLORdash Batten Quad D12", "watts": 175},
  {"id": "e37", "category": "Lighting - Moving Heads", "name": "Ayrton Diablo", "watts": 550},
  {"id": "e38", "category": "Lighting - Moving Heads", "name": "Ayrton Mistral", "watts": 450},
  {"id": "e39", "category": "Lighting - Moving Heads", "name": "Chauvet Color Strike M", "watts": 696},
  {"id": "e40", "category": "Lighting - Moving Heads", "name": "Chauvet DJ Intimidator Spot 255", "watts": 95},
  {"id": "e41", "category": "Lighting - Moving Heads", "name": "Chauvet DJ Intimidator Spot 375z (White)", "watts": 268},
  {"id": "e42", "category": "Lighting - Moving Heads", "name": "Chauvet Legend 412z", "watts": 188},
  {"id": "e43", "category": "Lighting - Moving Heads", "name": "Chauvet Rogue Outcast 1 BeamWash", "watts": 372},
  {"id": "e44", "category": "Lighting - Moving Heads", "name": "Chauvet Rogue Outcast 2X Wash", "watts": 282},
  {"id": "e45", "category": "Lighting - Moving Heads", "name": "Chauvet Rogue Outcast 3 Spot", "watts": 494},
  {"id": "e46", "category": "Lighting - Moving Heads", "name": "Chauvet Rogue R2 Spot", "watts": 301},
  {"id": "e47", "category": "Lighting - Moving Heads", "name": "Chauvet Rogue R2 Wash", "watts": 324},
  {"id": "e48", "category": "Lighting - Moving Heads", "name": "Clay Paky A.leda B-Eye K10", "watts": 450},
  {"id": "e49", "category": "Lighting - Moving Heads", "name": "Clay Paky AXCOR Beam 300", "watts": 215},
  {"id": "e50", "category": "Lighting - Moving Heads", "name": "Clay Paky AXCOR Spot 300", "watts": 340},
  {"id": "e51", "category": "Lighting - Moving Heads", "name": "Clay Paky Mythos 2", "watts": 700},
  {"id": "e52", "category": "Lighting - Moving Heads", "name": "Clay Paky Sharpy", "watts": 350},
  {"id": "e53", "category": "Lighting - Moving Heads", "name": "Robe LED Beam 150 (White)", "watts": 220},
  {"id": "e54", "category": "Lighting - Moving Heads", "name": "Robe SVB-1", "watts": 330},
  {"id": "e55", "category": "Lighting - Effects / Eye Candy", "name": "Beamz RB90", "watts": 400},
  {"id": "e56", "category": "Lighting - Effects / Eye Candy", "name": "Chauvet EPIX Drive 642 (16 EPIX Strip)", "watts": 278},
  {"id": "e57", "category": "Lighting - Effects / Eye Candy", "name": "eLumen8 Tri Pixel Panel 25 MKII", "watts": 780},
  {"id": "e58", "category": "Lighting - Effects / Eye Candy", "name": "Equinox Blitzer II Strobe", "watts": 25},
  {"id": "e59", "category": "Lighting - Effects / Eye Candy", "name": "Martin P3 Powerport 1500 (Up to 24 VDO Sceptron)", "watts": 1540},
  {"id": "e60", "category": "Lighting - Effects / Eye Candy", "name": "Robe Pickle PATT", "watts": 575},
  {"id": "e61", "category": "Lighting - Effects / Eye Candy", "name": "Showtec Pixel Bubble 75 (3m)", "watts": 121},
  {"id": "e62", "category": "Lighting - Effects / Eye Candy", "name": "Showtec Pixel Bubble 150 (6m)", "watts": 242},
  {"id": "e63", "category": "Lighting - Effects / Eye Candy", "name": "Showtec Stage Blinder FLEX Blaze 8 Way Kit", "watts": 700},
  {"id": "e64", "category": "Lighting - Effects / Eye Candy", "name": "Showtec Sunstrip Active DMX", "watts": 150},
  {"id": "e65", "category": "Lighting - Haze / Other", "name": "MDG ATME", "watts": 715},
  {"id": "e66", "category": "Lighting - Haze / Other", "name": "Chauvet Cumulus", "watts": 970},
  {"id": "e67", "category": "Lighting - Haze / Other", "name": "Unique 2.1", "watts": 1500},
  {"id": "e68", "category": "Vision - Control", "name": "Analog Way Pulse2-3G", "watts": 70},
  {"id": "e69", "category": "Vision - Control", "name": "Barco E2/E3/S3", "watts": 700},
  {"id": "e70", "category": "Vision - Control", "name": "Barco PDS 4k", "watts": 151},
  {"id": "e71", "category": "Vision - Control", "name": "Roland V-160", "watts": 55},
  {"id": "e72", "category": "Vision - Control", "name": "Roland V-1", "watts": 25.2},
  {"id": "e73", "category": "Vision - Control", "name": "Macbook", "watts": 96},
  {"id": "e74", "category": "Vision - Control", "name": "Defiance Laptop", "watts": 200},
  {"id": "e75", "category": "Vision - Control", "name": "Hippo Teka", "watts": 600},
  {"id": "e76", "category": "Vision - Control", "name": "Hippo Boreal", "watts": 800},
  {"id": "e77", "category": "Vision - LED", "name": "Absen PL2.5", "watts": 170},
  {"id": "e78", "category": "Vision - LED", "name": "Absen PL3.9", "watts": 135},
  {"id": "e79", "category": "Vision - LED", "name": "Absen PL3.9XL", "watts": 270},
  {"id": "e80", "category": "Vision - LED", "name": "Nova660", "watts": 20},
  {"id": "e81", "category": "Vision - LED", "name": "Nova4k", "watts": 30},
  {"id": "e82", "category": "Vision - Proj", "name": "Panasonic 6K", "watts": 820},
  {"id": "e83", "category": "Vision - Proj", "name": "Panasonic 10K", "watts": 1050},
  {"id": "e84", "category": "Vision - Proj", "name": "Panasonic 12K", "watts": 1030},
  {"id": "e85", "category": "Vision - Proj", "name": "Panasonic 21K", "watts": 1510},
  {"id": "e86", "category": "Vision - Displays", "name": "AOC 22\"", "watts": 18},
  {"id": "e87", "category": "Vision - Displays", "name": "Samsung 32\"", "watts": 72},
  {"id": "e88", "category": "Vision - Displays", "name": "Panasonic 43\"", "watts": 225},
  {"id": "e89", "category": "Vision - Displays", "name": "Panasonic 50\"", "watts": 255},
  {"id": "e90", "category": "Vision - Displays", "name": "Panasonic 55\"", "watts": 280},
  {"id": "e91", "category": "Vision - Displays", "name": "Panasonic 65\"", "watts": 340},
  {"id": "e92", "category": "Vision - Displays", "name": "Panasonic 75\"", "watts": 385},
  {"id": "e93", "category": "Vision - Displays", "name": "Panasonic 86\"", "watts": 580},
  {"id": "e94", "category": "Vision - Displays", "name": "LED Poster Board", "watts": 560},
  {"id": "e95", "category": "Rigging - Motors", "name": "EXE Rise D8+ 500kg", "watts": 800},
  {"id": "e96", "category": "Rigging - Motors", "name": "EXE Rise D8+ 1000kg", "watts": 1000},
  {"id": "e97", "category": "Rigging - Motors", "name": "Gis 250KG", "watts": 250},
  {"id": "e98", "category": "Expo Power Supplies", "name": "500 Watt Socket", "watts": 500},
  {"id": "e99", "category": "Expo Power Supplies", "name": "1000 Watt Socket", "watts": 1000},
  {"id": "e100", "category": "Expo Power Supplies", "name": "3000 Watt Socket", "watts": 3000},
  {"id": "e101", "category": "Expo Power Supplies", "name": "6000 Watt Socket", "watts": 6000},
];